# Generated by Django 4.0.3 on 2022-12-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0002_locationvo_import_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hats',
            name='color',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='hats',
            name='fabric',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='hats',
            name='style',
            field=models.CharField(max_length=250),
        ),
    ]
