# Generated by Django 4.0.3 on 2022-12-02 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0003_alter_hats_color_alter_hats_fabric_alter_hats_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.CharField(max_length=250)),
                ('style', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=250)),
                ('picture_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hat', to='hats_rest.locationvo')),
            ],
            options={
                'ordering': ('style', 'fabric'),
            },
        ),
        migrations.DeleteModel(
            name='Hats',
        ),
    ]
